#==============================================================================
# FILENAME: test_set.R
# PROJECT: 	Pooled testing HIV
# PURPOSE: derive the testing set from clean_data
# AUTHOR: Adam Brand

# CREATED:	20200302
# UPDATED: 	

# INPUT DATA: mydata - generated by program raw_data_clean.R				
# OUTPUT: 	

# R VERSION: R version 3.6.1 (2019-07-05) -- "Action of the Toes"
#==============================================================================
# Notes:
#
#
#
#
#
#
#
# =============================================================================
### set working directory to the location of the test_set.R program; location
### should also have the raw_data_clean.R program
setwd("")
source("raw_data_clean.R")
library(tidyverse)
library(broom)
library(glmnet)
library(ggplot2)
library(useful)
library(sbrl)
### running the data cleaning program


##### Program which splits the data into a testing set and a test set

### deriving the test set; minimum 6 month tes date was 2004-12-03
### maximum 6 month test date was 2011-12-19. 

## declaring the 6 month window for the testing set; grabbing all dates prior to 2010-04-01
date1 <- as.Date("2010-07-01")
date2 <- as.Date("2018-01-01")

##### selecting all VL measures within a 6 month window - there are no repeated subjects

# starting with the 6 month VLs; grabbing only observations with a 6 month VL in the date window defined by date1 and date2
# and have a basevl value
# below I am going to repeat these steps for values at 12 - 72 months, but will not repeat each comment
test.data6 <- mydata[(!is.na(mydata$visitdate6) & !is.na(mydata$vl_mth6) & mydata$visitdate6 <= date2 & mydata$visitdate6 >= date1),]
# creating variable for previous vl (prev_vl) andtime since prev_vl (prev_vl_t)
test.data6$prev_vl <- test.data6$basevl
test.data6$prev_vl_t <- 6
# keeping only records with a previous vl value
test.data6 <- test.data6[!is.na(test.data6$prev_vl),]

# creating variable prev_fail which is the number of previous treatment failures; because the last record is baseline, nobody will
# have an observed previous treatment failure
test.data6$prev_fail=0

# creating an indicator variabe for whether the VL is from visit date 6 or not
test.data6$visit <- 6

# creating a variable for VL which doesn't depend on visit (both raw and log10)
test.data6$vl <- test.data6$vl_mth6
test.data6$vllog <- test.data6$vl6

#creating a variable for experiencing a double failure at 6 months - defined as 2 consecutive, post-baseline failures
# by def'n there cannt be at 6 months, so all records set to 0
test.data6$dub_fail <- NA




# doing the same for 12 month values
test.data12 <- mydata[(!is.na(mydata$visitdate12) & !is.na(mydata$vl_mth12) & mydata$visitdate12 <= date2 & mydata$visitdate12 >= date1),]

# maiing sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data12$study_id)){
  if (!is.na(test.data12$vl_mth6[i]))
  {test.data12$prev_vl[i]=test.data12$vl_mth6[i]
  test.data12$prev_vl_t[i]=6}
  else if (!is.na(test.data12$basevl[i]))
  {test.data12$prev_vl[i]=test.data12$basevl[i]
  test.data12$prev_vl_t[i]=12}
  else {test.data12$prev_vl[i]=NA}
}

test.data12 <- test.data12[!is.na(test.data12$prev_vl),]

for (i in 1:length(test.data12$study_id)) {
  if (!is.na(test.data12$basevl[i]) & test.data12$basevl[i] < 1000 & !is.na(test.data12$vl_mth6[i]) & test.data12$vl_mth6[i] >= 1000)
  {test.data12$prev_fail[i]=1}
  else {test.data12$prev_fail[i]=0}
}

test.data12$visit=12

test.data12$vl <- test.data12$vl_mth12
test.data12$vllog <- test.data12$vl12

### getting the double failure status at month 12
for (i in 1:length(test.data12$study_id)) {
  if (!is.na(test.data12$prev_vl[i]) & test.data12$prev_vl_t[i]<12 & test.data12$prev_vl[i]>=1000 & test.data12$vl_mth12[i]>=1000)
  {test.data12$dub_fail[i] = 1}
  else if (!is.na(test.data12$prev_vl[i]) & test.data12$prev_vl_t[i]<12 & (test.data12$prev_vl[i]<1000 | test.data12$vl_mth12[i]<1000))
  {test.data12$dub_fail[i] = 0}
  else {test.data12$dub_fail[i] = NA}
}

check <- test.data12[is.na(test.data12$dub_fail),]
check2 <- test.data12[!is.na(test.data12$dub_fail),]
check3 <- test.data12[test.data12$dub_fail==1 & !is.na(test.data12$dub_fail),]

# repeating for 18 month values
test.data18 <- mydata[(!is.na(mydata$visitdate18) & !is.na(mydata$vl_mth18) & mydata$visitdate18 <= date2 & mydata$visitdate18 >= date1),]
sum(duplicated(test.data18$study_id))

# maiking sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data18$study_id)){
  if (!is.na(test.data18$vl_mth12[i]))
  {test.data18$prev_vl[i]=test.data18$vl_mth12[i]
  test.data18$prev_vl_t[i]=6}
  else if (!is.na(test.data18$vl_mth6[i]))
  {test.data18$prev_vl[i]=test.data18$vl_mth6[i]
  test.data18$prev_vl_t[i]=12}
  else if (!is.na(test.data18$basevl[i]))
  {test.data18$prev_vl[i]=test.data18$basevl[i]
  test.data18$prev_vl_t[i]=18}
  else {test.data18$prev_vl[i]=NA}
}

test.data18 <- test.data18[!is.na(test.data18$prev_vl),]

counter <- NULL
for (i in 1:length(test.data18$study_id)) {
  counter[i] <- 0
  # checking for previous failures at 6 months
  if (!is.na(test.data18$basevl[i]) & test.data18$basevl[i] < 1000 & !is.na(test.data18$vl_mth6[i]) & test.data18$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 12 months
  if (((!is.na(test.data18$vl_mth6[i]) & test.data18$vl_mth6[i] < 1000) | 
       (is.na(test.data18$vl_mth6[i]) & !is.na(test.data18$basevl[i]) & test.data18$basevl[i] < 1000)) 
      & !is.na(test.data18$vl_mth12[i]) & test.data18$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  test.data18$prev_fail[i]=counter[i]
}

test.data18$visit=18

test.data18$vl <- test.data18$vl_mth18
test.data18$vllog <- test.data18$vl18

### getting the double failure status at month 18
for (i in 1:length(test.data18$study_id)) {
  if (!is.na(test.data18$prev_vl[i]) & test.data18$prev_vl_t[i]<18 & test.data18$prev_vl[i]>=1000 & test.data18$vl_mth18[i]>=1000)
  {test.data18$dub_fail[i] = 1}
  else if (!is.na(test.data18$prev_vl[i]) & test.data18$prev_vl_t[i]<18 & (test.data18$prev_vl[i]<1000 | test.data18$vl_mth18[i]<1000))
  {test.data18$dub_fail[i] = 0}
  else {test.data18$dub_fail[i] = NA}
}

check <- test.data18[is.na(test.data18$dub_fail),]
check2 <- test.data18[!is.na(test.data18$dub_fail),]
check3 <- test.data18[test.data18$dub_fail==1 & !is.na(test.data18$dub_fail),]


# repeating for 24 month values
test.data24 <- mydata[(!is.na(mydata$visitdate24) & !is.na(mydata$vl_mth24) & mydata$visitdate24 <= date2 & mydata$visitdate24 >= date1),]

# maiing sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data24$study_id)){
  if (!is.na(test.data24$vl_mth18[i])) {
    test.data24$prev_vl[i]=test.data24$vl_mth18[i]
    test.data24$prev_vl_t[i]=6
  }
  else if (!is.na(test.data24$vl_mth12[i]))
  {test.data24$prev_vl[i]=test.data24$vl_mth12[i]
  test.data24$prev_vl_t[i]=12}
  else if (!is.na(test.data24$vl_mth6[i]))
  {test.data24$prev_vl[i]=test.data24$vl_mth6[i]
  test.data24$prev_vl_t[i]=18}
  else if (!is.na(test.data24$basevl[i]))
  {test.data24$prev_vl[i]=test.data24$basevl[i]
  test.data24$prev_vl_t[i]=24}
  else {test.data24$prev_vl[i]=NA}
}

test.data24 <- test.data24[!is.na(test.data24$prev_vl),]

counter <- NULL
for (i in 1:length(test.data24$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data24$basevl[i]) & test.data24$basevl[i] < 1000 & !is.na(test.data24$vl_mth6[i]) & test.data24$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data24$vl_mth6[i]) & test.data24$vl_mth6[i] < 1000) | 
       (is.na(test.data24$vl_mth6[i]) & !is.na(test.data24$basevl[i]) & test.data24$basevl[i] < 1000)) 
      & !is.na(test.data24$vl_mth12[i]) & test.data24$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data24$vl_mth12[i]) & test.data24$vl_mth12[i] < 1000) |
       (is.na(test.data24$vl_mth12[i]) & !is.na(test.data24$vl_mth6[i]) & test.data24$vl_mth6[i] < 1000) |
       (is.na(test.data24$vl_mth12[i]) & is.na(test.data24$vl_mth6[i]) & !is.na(test.data24$basevl[i]) & test.data24$basevl[i] < 1000))
      & !is.na(test.data24$vl_mth18[i]) & test.data24$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  test.data24$prev_fail[i]=counter[i]
}

test.data24$visit=24

test.data24$vl <- test.data24$vl_mth24
test.data24$vllog <- test.data24$vl24

### getting the double failure status at month 24
for (i in 1:length(test.data24$study_id)) {
  if (!is.na(test.data24$prev_vl[i]) & test.data24$prev_vl_t[i]<24 & test.data24$prev_vl[i]>=1000 & test.data24$vl_mth24[i]>=1000)
  {test.data24$dub_fail[i] = 1}
  else if (!is.na(test.data24$prev_vl[i]) & test.data24$prev_vl_t[i]<24 & (test.data24$prev_vl[i]<1000 | test.data24$vl_mth24[i]<1000))
  {test.data24$dub_fail[i] = 0}
  else {test.data24$dub_fail[i] = NA}
}

check <- test.data24[is.na(test.data24$dub_fail),]
check2 <- test.data24[!is.na(test.data24$dub_fail),]
check3 <- test.data24[test.data24$dub_fail==1 & !is.na(test.data24$dub_fail),]

# repeating for 30 month values
test.data30 <- mydata[(!is.na(mydata$visitdate30) & !is.na(mydata$vl_mth30) & mydata$visitdate30 <= date2 & mydata$visitdate30 >= date1),]

# maiking sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data30$study_id)){
  if (!is.na(test.data30$vl_mth24[i])){
    test.data30$prev_vl[i]=test.data30$vl_mth24[i]
    test.data30$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data30$vl_mth18[i])) {
    test.data30$prev_vl[i]=test.data30$vl_mth18[i]
    test.data30$prev_vl_t[i]=12
  }
  else if (!is.na(test.data30$vl_mth12[i]))
  {test.data30$prev_vl[i]=test.data30$vl_mth12[i]
  test.data30$prev_vl_t[i]=18}
  else if (!is.na(test.data30$vl_mth6[i]))
  {test.data30$prev_vl[i]=test.data30$vl_mth6[i]
  test.data30$prev_vl_t[i]=24}
  else if (!is.na(test.data30$basevl[i]))
  {test.data30$prev_vl[i]=test.data30$basevl[i]
  test.data30$prev_vl_t[i]=30}
  else {test.data30$prev_vl[i]=NA}
}

test.data30 <- test.data30[!is.na(test.data30$prev_vl),]

counter <- NULL
for (i in 1:length(test.data30$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data30$basevl[i]) & test.data30$basevl[i] < 1000 & !is.na(test.data30$vl_mth6[i]) & test.data30$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data30$vl_mth6[i]) & test.data30$vl_mth6[i] < 1000) | 
       (is.na(test.data30$vl_mth6[i]) & !is.na(test.data30$basevl[i]) & test.data30$basevl[i] < 1000)) 
      & !is.na(test.data30$vl_mth12[i]) & test.data30$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data30$vl_mth12[i]) & test.data30$vl_mth12[i] < 1000) |
       (is.na(test.data30$vl_mth12[i]) & !is.na(test.data30$vl_mth6[i]) & test.data30$vl_mth6[i] < 1000) |
       (is.na(test.data30$vl_mth12[i]) & is.na(test.data30$vl_mth6[i]) & !is.na(test.data30$basevl[i]) & test.data30$basevl[i] < 1000))
      & !is.na(test.data30$vl_mth18[i]) & test.data30$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data30$vl_mth18[i]) & test.data30$vl_mth18[i] < 1000) |
       (is.na(test.data30$vl_mth18[i]) & !is.na(test.data30$vl_mth12[i]) & test.data30$vl_mth12[i] < 1000) |
       (is.na(test.data30$vl_mth18[i]) & is.na(test.data30$vl_mth12[i]) & !is.na(test.data30$vl_mth6[i]) & test.data30$vl_mth6[i] < 1000) |
       (is.na(test.data30$vl_mth18[i]) & is.na(test.data30$vl_mth12[i]) & is.na(test.data30$vl_mth6[i]) & !is.na(test.data30$basevl[i]) & test.data30$basevl[i] < 1000))
      & !is.na(test.data30$vl_mth24[i]) & test.data30$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data30$prev_fail[i]=counter[i]
}

test.data30$visit=30

test.data30$vl <- test.data30$vl_mth30
test.data30$vllog <- test.data30$vl30

### getting the double failure status at month 30
for (i in 1:length(test.data30$study_id)) {
  if (!is.na(test.data30$prev_vl[i]) & test.data30$prev_vl_t[i]<30 & test.data30$prev_vl[i]>=1000 & test.data30$vl_mth30[i]>=1000)
  {test.data30$dub_fail[i] = 1}
  else if (!is.na(test.data30$prev_vl[i]) & test.data30$prev_vl_t[i]<30 & (test.data30$prev_vl[i]<1000 | test.data30$vl_mth30[i]<1000))
  {test.data30$dub_fail[i] = 0}
  else {test.data30$dub_fail[i] = NA}
}

check <- test.data30[is.na(test.data30$dub_fail),]
check2 <- test.data30[!is.na(test.data30$dub_fail),]
check3 <- test.data30[test.data30$dub_fail==1 & !is.na(test.data30$dub_fail),]

# repeating for 36 month values
test.data36 <- mydata[(!is.na(mydata$visitdate36) & !is.na(mydata$vl_mth36) & mydata$visitdate36 <= date2 & mydata$visitdate36 >= date1),]

# maiking sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data36$study_id)){
  if (!is.na(test.data36$vl_mth30[i])){
    test.data36$prev_vl[i]=test.data36$vl_mth30[i]
    test.data36$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data36$vl_mth24[i])){
    test.data36$prev_vl[i]=test.data36$vl_mth24[i]
    test.data36$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data36$vl_mth18[i])) {
    test.data36$prev_vl[i]=test.data36$vl_mth18[i]
    test.data36$prev_vl_t[i]=18
  }
  else if (!is.na(test.data36$vl_mth12[i]))
  {test.data36$prev_vl[i]=test.data36$vl_mth12[i]
  test.data36$prev_vl_t[i]=24}
  else if (!is.na(test.data36$vl_mth6[i]))
  {test.data36$prev_vl[i]=test.data36$vl_mth6[i]
  test.data36$prev_vl_t[i]=30}
  else if (!is.na(test.data36$basevl[i]))
  {test.data36$prev_vl[i]=test.data36$basevl[i]
  test.data36$prev_vl_t[i]=36}
  else {test.data36$prev_vl[i]=NA}
}

test.data36 <- test.data36[!is.na(test.data36$prev_vl),]

counter <- NULL
for (i in 1:length(test.data36$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data36$basevl[i]) & test.data36$basevl[i] < 1000 & !is.na(test.data36$vl_mth6[i]) & test.data36$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data36$vl_mth6[i]) & test.data36$vl_mth6[i] < 1000) | 
       (is.na(test.data36$vl_mth6[i]) & !is.na(test.data36$basevl[i]) & test.data36$basevl[i] < 1000)) 
      & !is.na(test.data36$vl_mth12[i]) & test.data36$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data36$vl_mth12[i]) & test.data36$vl_mth12[i] < 1000) |
       (is.na(test.data36$vl_mth12[i]) & !is.na(test.data36$vl_mth6[i]) & test.data36$vl_mth6[i] < 1000) |
       (is.na(test.data36$vl_mth12[i]) & is.na(test.data36$vl_mth6[i]) & !is.na(test.data36$basevl[i]) & test.data36$basevl[i] < 1000))
      & !is.na(test.data36$vl_mth18[i]) & test.data36$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data36$vl_mth18[i]) & test.data36$vl_mth18[i] < 1000) |
       (is.na(test.data36$vl_mth18[i]) & !is.na(test.data36$vl_mth12[i]) & test.data36$vl_mth12[i] < 1000) |
       (is.na(test.data36$vl_mth18[i]) & is.na(test.data36$vl_mth12[i]) & !is.na(test.data36$vl_mth6[i]) & test.data36$vl_mth6[i] < 1000) |
       (is.na(test.data36$vl_mth18[i]) & is.na(test.data36$vl_mth12[i]) & is.na(test.data36$vl_mth6[i]) & !is.na(test.data36$basevl[i]) & test.data36$basevl[i] < 1000))
      & !is.na(test.data36$vl_mth24[i]) & test.data36$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data36$vl_mth24[i]) & test.data36$vl_mth24[i] < 1000) |
       (is.na(test.data36$vl_mth24[i]) & !is.na(test.data36$vl_mth18[i]) & test.data36$vl_mth18[i] < 1000) |
       (is.na(test.data36$vl_mth24[i]) & is.na(test.data36$vl_mth18[i]) & !is.na(test.data36$vl_mth12[i]) & test.data36$vl_mth12[i] < 1000) |
       (is.na(test.data36$vl_mth24[i]) & is.na(test.data36$vl_mth18[i]) & is.na(test.data36$vl_mth12[i]) & !is.na(test.data36$vl_mth6[i]) & test.data36$vl_mth6[i] < 1000) |
       (is.na(test.data36$vl_mth24[i]) & is.na(test.data36$vl_mth18[i]) & is.na(test.data36$vl_mth12[i]) & is.na(test.data36$vl_mth6[i]) & !is.na(test.data36$basevl[i]) & test.data36$basevl[i] < 1000))
      & !is.na(test.data36$vl_mth30[i]) & test.data36$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data36$prev_fail[i]=counter[i]
}

test.data36$visit=36

test.data36$vl <- test.data36$vl_mth36
test.data36$vllog <- test.data36$vl36

### getting the double failure status at month 36
for (i in 1:length(test.data36$study_id)) {
  if (!is.na(test.data36$prev_vl[i]) & test.data36$prev_vl_t[i]<36 & test.data36$prev_vl[i]>=1000 & test.data36$vl_mth36[i]>=1000)
  {test.data36$dub_fail[i] = 1}
  else if (!is.na(test.data36$prev_vl[i]) & test.data36$prev_vl_t[i]<36 & (test.data36$prev_vl[i]<1000 | test.data36$vl_mth36[i]<1000))
  {test.data36$dub_fail[i] = 0}
  else {test.data36$dub_fail[i] = NA}
}

check <- test.data36[is.na(test.data36$dub_fail),]
check2 <- test.data36[!is.na(test.data36$dub_fail),]
check3 <- test.data36[test.data36$dub_fail==1 & !is.na(test.data36$dub_fail),]



# repeating for 42 month values
test.data42 <- mydata[(!is.na(mydata$visitdate42) & !is.na(mydata$vl_mth42) & mydata$visitdate42 <= date2 & mydata$visitdate42 >= date1),]

# maiking sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data42$study_id)){
  if (!is.na(test.data42$vl_mth36[i])) {
    test.data42$prev_vl[i]=test.data42$vl_mth36[i]
    test.data42$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data42$vl_mth30[i])){
    test.data42$prev_vl[i]=test.data42$vl_mth30[i]
    test.data42$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data42$vl_mth24[i])){
    test.data42$prev_vl[i]=test.data42$vl_mth24[i]
    test.data42$prev_vl_t[i]=18
  }
  
  else if (!is.na(test.data42$vl_mth18[i])) {
    test.data42$prev_vl[i]=test.data42$vl_mth18[i]
    test.data42$prev_vl_t[i]=24
  }
  else if (!is.na(test.data42$vl_mth12[i]))
  {test.data42$prev_vl[i]=test.data42$vl_mth12[i]
  test.data42$prev_vl_t[i]=30}
  else if (!is.na(test.data42$vl_mth6[i]))
  {test.data42$prev_vl[i]=test.data42$vl_mth6[i]
  test.data42$prev_vl_t[i]=36}
  else if (!is.na(test.data42$basevl[i]))
  {test.data42$prev_vl[i]=test.data42$basevl[i]
  test.data42$prev_vl_t[i]=42}
  else {test.data42$prev_vl[i]=NA}
}

test.data42 <- test.data42[!is.na(test.data42$prev_vl),]

counter <- NULL
for (i in 1:length(test.data42$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000 & !is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] < 1000) | 
       (is.na(test.data42$vl_mth6[i]) & !is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000)) 
      & !is.na(test.data42$vl_mth12[i]) & test.data42$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data42$vl_mth12[i]) & test.data42$vl_mth12[i] < 1000) |
       (is.na(test.data42$vl_mth12[i]) & !is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] < 1000) |
       (is.na(test.data42$vl_mth12[i]) & is.na(test.data42$vl_mth6[i]) & !is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000))
      & !is.na(test.data42$vl_mth18[i]) & test.data42$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data42$vl_mth18[i]) & test.data42$vl_mth18[i] < 1000) |
       (is.na(test.data42$vl_mth18[i]) & !is.na(test.data42$vl_mth12[i]) & test.data42$vl_mth12[i] < 1000) |
       (is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & !is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] < 1000) |
       (is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & is.na(test.data42$vl_mth6[i]) & !is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000))
      & !is.na(test.data42$vl_mth24[i]) & test.data42$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data42$vl_mth24[i]) & test.data42$vl_mth24[i] < 1000) |
       (is.na(test.data42$vl_mth24[i]) & !is.na(test.data42$vl_mth18[i]) & test.data42$vl_mth18[i] < 1000) |
       (is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth18[i]) & !is.na(test.data42$vl_mth12[i]) & test.data42$vl_mth12[i] < 1000) |
       (is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & !is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] < 1000) |
       (is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & is.na(test.data42$vl_mth6[i]) & !is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000))
      & !is.na(test.data42$vl_mth30[i]) & test.data42$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data42$vl_mth30[i]) & test.data42$vl_mth30[i] < 1000) |
       (is.na(test.data42$vl_mth30[i]) & !is.na(test.data42$vl_mth24[i]) & test.data42$vl_mth24[i] < 1000) |
       (is.na(test.data42$vl_mth30[i]) & is.na(test.data42$vl_mth24[i]) & !is.na(test.data42$vl_mth24[i]) & test.data42$vl_mth24[i] < 1000) |
       (is.na(test.data42$vl_mth30[i]) & is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth24[i]) & !is.na(test.data42$vl_mth12[i]) & test.data42$vl_mth12[i] < 1000) |
       (is.na(test.data42$vl_mth30[i]) & is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & !is.na(test.data42$vl_mth6[i]) & test.data42$vl_mth6[i] < 1000) |
       (is.na(test.data42$vl_mth30[i]) & is.na(test.data42$vl_mth24[i]) & is.na(test.data42$vl_mth18[i]) & is.na(test.data42$vl_mth12[i]) & is.na(test.data42$vl_mth6[i]) & !is.na(test.data42$basevl[i]) & test.data42$basevl[i] < 1000))
      & !is.na(test.data42$vl_mth36[i]) & test.data42$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data42$prev_fail[i]=counter[i]
}

test.data42$visit=42

test.data42$vl <- test.data42$vl_mth42
test.data42$vllog <- test.data42$vl42

### getting the double failure status at month 42
for (i in 1:length(test.data42$study_id)) {
  if (!is.na(test.data42$prev_vl[i]) & test.data42$prev_vl_t[i]<42 & test.data42$prev_vl[i]>=1000 & test.data42$vl_mth42[i]>=1000)
  {test.data42$dub_fail[i] = 1}
  else if (!is.na(test.data42$prev_vl[i]) & test.data42$prev_vl_t[i]<42 & (test.data42$prev_vl[i]<1000 | test.data42$vl_mth42[i]<1000))
  {test.data42$dub_fail[i] = 0}
  else {test.data42$dub_fail[i] = NA}
}

check <- test.data42[is.na(test.data42$dub_fail),]
check2 <- test.data42[!is.na(test.data42$dub_fail),]
check3 <- test.data42[test.data42$dub_fail==1 & !is.na(test.data42$dub_fail),]


# repeating for 48 month values
test.data48 <- mydata[(!is.na(mydata$visitdate48) & !is.na(mydata$vl_mth48) & mydata$visitdate48 <= date2 & mydata$visitdate48 >= date1),]

# maiking sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data48$study_id)){
  if (!is.na(test.data48$vl_mth42[i])){
    test.data48$prev_vl[i]=test.data48$vl_mth42[i]
    test.data48$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data48$vl_mth36[i])) {
    test.data48$prev_vl[i]=test.data48$vl_mth36[i]
    test.data48$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data48$vl_mth30[i])){
    test.data48$prev_vl[i]=test.data48$vl_mth30[i]
    test.data48$prev_vl_t[i]=18
  }
  
  else if (!is.na(test.data48$vl_mth24[i])){
    test.data48$prev_vl[i]=test.data48$vl_mth24[i]
    test.data48$prev_vl_t[i]=24
  }
  
  else if (!is.na(test.data48$vl_mth18[i])) {
    test.data48$prev_vl[i]=test.data48$vl_mth18[i]
    test.data48$prev_vl_t[i]=30
  }
  else if (!is.na(test.data48$vl_mth12[i]))
  {test.data48$prev_vl[i]=test.data48$vl_mth12[i]
  test.data48$prev_vl_t[i]=36}
  else if (!is.na(test.data48$vl_mth6[i]))
  {test.data48$prev_vl[i]=test.data48$vl_mth6[i]
  test.data48$prev_vl_t[i]=42}
  else if (!is.na(test.data48$basevl[i]))
  {test.data48$prev_vl[i]=test.data48$basevl[i]
  test.data48$prev_vl_t[i]=48}
  else {test.data48$prev_vl[i]=NA}
}

test.data48 <- test.data48[!is.na(test.data48$prev_vl),]

counter <- NULL
for (i in 1:length(test.data48$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000 & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) | 
       (is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000)) 
      & !is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] < 1000) |
       (is.na(test.data48$vl_mth12[i]) & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) |
       (is.na(test.data48$vl_mth12[i]) & is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000))
      & !is.na(test.data48$vl_mth18[i]) & test.data48$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data48$vl_mth18[i]) & test.data48$vl_mth18[i] < 1000) |
       (is.na(test.data48$vl_mth18[i]) & !is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] < 1000) |
       (is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) |
       (is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000))
      & !is.na(test.data48$vl_mth24[i]) & test.data48$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data48$vl_mth24[i]) & test.data48$vl_mth24[i] < 1000) |
       (is.na(test.data48$vl_mth24[i]) & !is.na(test.data48$vl_mth18[i]) & test.data48$vl_mth18[i] < 1000) |
       (is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & !is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] < 1000) |
       (is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) |
       (is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000))
      & !is.na(test.data48$vl_mth30[i]) & test.data48$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data48$vl_mth30[i]) & test.data48$vl_mth30[i] < 1000) |
       (is.na(test.data48$vl_mth30[i]) & !is.na(test.data48$vl_mth24[i]) & test.data48$vl_mth24[i] < 1000) |
       (is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & !is.na(test.data48$vl_mth24[i]) & test.data48$vl_mth24[i] < 1000) |
       (is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth24[i]) & !is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] < 1000) |
       (is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) |
       (is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000))
      & !is.na(test.data48$vl_mth36[i]) & test.data48$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 42 months
  if (((!is.na(test.data48$vl_mth36[i]) & test.data48$vl_mth36[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & !is.na(test.data48$vl_mth30[i]) & test.data48$vl_mth30[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & is.na(test.data48$vl_mth30[i]) & !is.na(test.data48$vl_mth24[i]) & test.data48$vl_mth24[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & !is.na(test.data48$vl_mth18[i]) & test.data48$vl_mth18[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & !is.na(test.data48$vl_mth12[i]) & test.data48$vl_mth12[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & !is.na(test.data48$vl_mth6[i]) & test.data48$vl_mth6[i] < 1000) |
       (is.na(test.data48$vl_mth36[i]) & is.na(test.data48$vl_mth30[i]) & is.na(test.data48$vl_mth24[i]) & is.na(test.data48$vl_mth18[i]) & is.na(test.data48$vl_mth12[i]) & is.na(test.data48$vl_mth6[i]) & !is.na(test.data48$basevl[i]) & test.data48$basevl[i] < 1000))
      & !is.na(test.data48$vl_mth42[i]) & test.data48$vl_mth42[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data48$prev_fail[i]=counter[i]
}

test.data48$visit=48

test.data48$vl <- test.data48$vl_mth48
test.data48$vllog <- test.data48$vl48

### getting the double failure status at month 48
for (i in 1:length(test.data48$study_id)) {
  if (!is.na(test.data48$prev_vl[i]) & test.data48$prev_vl_t[i]<48 & test.data48$prev_vl[i]>=1000 & test.data48$vl_mth48[i]>=1000)
  {test.data48$dub_fail[i] = 1}
  else if (!is.na(test.data48$prev_vl[i]) & test.data48$prev_vl_t[i]<48 & (test.data48$prev_vl[i]<1000 | test.data48$vl_mth48[i]<1000))
  {test.data48$dub_fail[i] = 0}
  else {test.data48$dub_fail[i] = NA}
}

check <- test.data48[is.na(test.data48$dub_fail),]
check2 <- test.data48[!is.na(test.data48$dub_fail),]
check3 <- test.data48[test.data48$dub_fail==1 & !is.na(test.data48$dub_fail),]




# repeating for 54 month values
test.data54 <- mydata[(!is.na(mydata$visitdate54) & !is.na(mydata$vl_mth54) & mydata$visitdate54 <= date2 & mydata$visitdate54 >= date1),]

# making sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data54$study_id)){
  
  if (!is.na(test.data54$vl_mth48[i])){
    test.data54$prev_vl[i]=test.data54$vl_mth48[i]
    test.data54$prev_vl_t[i]=6
  }
  else if (!is.na(test.data54$vl_mth42[i])){
    test.data54$prev_vl[i]=test.data54$vl_mth42[i]
    test.data54$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data54$vl_mth36[i])) {
    test.data54$prev_vl[i]=test.data54$vl_mth36[i]
    test.data54$prev_vl_t[i]=18
  }
  
  else if (!is.na(test.data54$vl_mth30[i])){
    test.data54$prev_vl[i]=test.data54$vl_mth30[i]
    test.data54$prev_vl_t[i]=24
  }
  
  else if (!is.na(test.data54$vl_mth24[i])){
    test.data54$prev_vl[i]=test.data54$vl_mth24[i]
    test.data54$prev_vl_t[i]=30
  }
  
  else if (!is.na(test.data54$vl_mth18[i])) {
    test.data54$prev_vl[i]=test.data54$vl_mth18[i]
    test.data54$prev_vl_t[i]=36
  }
  else if (!is.na(test.data54$vl_mth12[i]))
  {test.data54$prev_vl[i]=test.data54$vl_mth12[i]
  test.data54$prev_vl_t[i]=42}
  else if (!is.na(test.data54$vl_mth6[i]))
  {test.data54$prev_vl[i]=test.data54$vl_mth6[i]
  test.data54$prev_vl_t[i]=48}
  else if (!is.na(test.data54$basevl[i]))
  {test.data54$prev_vl[i]=test.data54$basevl[i]
  test.data54$prev_vl_t[i]=54}
  else {test.data54$prev_vl[i]=NA}
}

test.data54 <- test.data54[!is.na(test.data54$prev_vl),]

counter <- NULL
for (i in 1:length(test.data54$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000 & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) | 
       (is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000)) 
      & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) |
       (is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth18[i]) & test.data54$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data54$vl_mth18[i]) & test.data54$vl_mth18[i] < 1000) |
       (is.na(test.data54$vl_mth18[i]) & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) |
       (is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] < 1000) |
       (is.na(test.data54$vl_mth24[i]) & !is.na(test.data54$vl_mth18[i]) & test.data54$vl_mth18[i] < 1000) |
       (is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) |
       (is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth30[i]) & test.data54$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data54$vl_mth30[i]) & test.data54$vl_mth30[i] < 1000) |
       (is.na(test.data54$vl_mth30[i]) & !is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] < 1000) |
       (is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & !is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] < 1000) |
       (is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth24[i]) & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) |
       (is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth36[i]) & test.data54$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 42 months
  if (((!is.na(test.data54$vl_mth36[i]) & test.data54$vl_mth36[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & !is.na(test.data54$vl_mth30[i]) & test.data54$vl_mth30[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & !is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & !is.na(test.data54$vl_mth18[i]) & test.data54$vl_mth18[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) |
       (is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth42[i]) & test.data54$vl_mth42[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 48 months
  if (((!is.na(test.data54$vl_mth42[i]) & test.data54$vl_mth42[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & !is.na(test.data54$vl_mth36[i]) & test.data54$vl_mth36[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & !is.na(test.data54$vl_mth30[i]) & test.data54$vl_mth30[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & !is.na(test.data54$vl_mth24[i]) & test.data54$vl_mth24[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & !is.na(test.data54$vl_mth18[i]) & test.data54$vl_mth18[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & !is.na(test.data54$vl_mth12[i]) & test.data54$vl_mth12[i] < 1000) |
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & !is.na(test.data54$vl_mth6[i]) & test.data54$vl_mth6[i] < 1000) | 
       (is.na(test.data54$vl_mth42[i]) & is.na(test.data54$vl_mth36[i]) & is.na(test.data54$vl_mth30[i]) & is.na(test.data54$vl_mth24[i]) & is.na(test.data54$vl_mth18[i]) & is.na(test.data54$vl_mth12[i]) & is.na(test.data54$vl_mth6[i]) & !is.na(test.data54$basevl[i]) & test.data54$basevl[i] < 1000))
      & !is.na(test.data54$vl_mth48[i]) & test.data54$vl_mth48[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data54$prev_fail[i]=counter[i]
}

test.data54$visit=54

test.data54$vl <- test.data54$vl_mth54
test.data54$vllog <- test.data54$vl54

### getting the double failure status at month 54
for (i in 1:length(test.data54$study_id)) {
  if (!is.na(test.data54$prev_vl[i]) & test.data54$prev_vl_t[i]<54 & test.data54$prev_vl[i]>=1000 & test.data54$vl_mth54[i]>=1000)
  {test.data54$dub_fail[i] = 1}
  else if (!is.na(test.data54$prev_vl[i]) & test.data54$prev_vl_t[i]<54 & (test.data54$prev_vl[i]<1000 | test.data54$vl_mth54[i]<1000))
  {test.data54$dub_fail[i] = 0}
  else {test.data54$dub_fail[i] = NA}
}

check <- test.data54[is.na(test.data54$dub_fail),]
check2 <- test.data54[!is.na(test.data54$dub_fail),]
check3 <- test.data54[test.data54$dub_fail==1 & !is.na(test.data54$dub_fail),]


# repeating for 60 month values
test.data60 <- mydata[(!is.na(mydata$visitdate60) & !is.na(mydata$vl_mth60) & mydata$visitdate60 <= date2 & mydata$visitdate60 >= date1),]

# making sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data60$study_id)){
  
  if (!is.na(test.data60$vl_mth54[i])){
    test.data60$prev_vl[i]=test.data60$vl_mth54[i]
    test.data60$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data60$vl_mth48[i])){
    test.data60$prev_vl[i]=test.data60$vl_mth48[i]
    test.data60$prev_vl_t[i]=12
  }
  else if (!is.na(test.data60$vl_mth42[i])){
    test.data60$prev_vl[i]=test.data60$vl_mth42[i]
    test.data60$prev_vl_t[i]=18
  }
  
  else if (!is.na(test.data60$vl_mth36[i])) {
    test.data60$prev_vl[i]=test.data60$vl_mth36[i]
    test.data60$prev_vl_t[i]=24
  }
  
  else if (!is.na(test.data60$vl_mth30[i])){
    test.data60$prev_vl[i]=test.data60$vl_mth30[i]
    test.data60$prev_vl_t[i]=30
  }
  
  else if (!is.na(test.data60$vl_mth24[i])){
    test.data60$prev_vl[i]=test.data60$vl_mth24[i]
    test.data60$prev_vl_t[i]=36
  }
  
  else if (!is.na(test.data60$vl_mth18[i])) {
    test.data60$prev_vl[i]=test.data60$vl_mth18[i]
    test.data60$prev_vl_t[i]=42
  }
  else if (!is.na(test.data60$vl_mth12[i]))
  {test.data60$prev_vl[i]=test.data60$vl_mth12[i]
  test.data60$prev_vl_t[i]=48}
  else if (!is.na(test.data60$vl_mth6[i]))
  {test.data60$prev_vl[i]=test.data60$vl_mth6[i]
  test.data60$prev_vl_t[i]=54}
  else if (!is.na(test.data60$basevl[i]))
  {test.data60$prev_vl[i]=test.data60$basevl[i]
  test.data60$prev_vl_t[i]=60}
  else {test.data60$prev_vl[i]=NA}
}

test.data60 <- test.data60[!is.na(test.data60$prev_vl),]

counter <- NULL
for (i in 1:length(test.data60$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000 & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) | 
       (is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000)) 
      & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] < 1000) |
       (is.na(test.data60$vl_mth18[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] < 1000) |
       (is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth30[i]) & test.data60$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data60$vl_mth30[i]) & test.data60$vl_mth30[i] < 1000) |
       (is.na(test.data60$vl_mth30[i]) & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth36[i]) & test.data60$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 42 months
  if (((!is.na(test.data60$vl_mth36[i]) & test.data60$vl_mth36[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & !is.na(test.data60$vl_mth30[i]) & test.data60$vl_mth30[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth42[i]) & test.data60$vl_mth42[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 48 months
  if (((!is.na(test.data60$vl_mth42[i]) & test.data60$vl_mth42[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & !is.na(test.data60$vl_mth36[i]) & test.data60$vl_mth36[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & !is.na(test.data60$vl_mth30[i]) & test.data60$vl_mth30[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) |
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) | 
       (is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth48[i]) & test.data60$vl_mth48[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 54 months
  if (((!is.na(test.data60$vl_mth48[i]) & test.data60$vl_mth48[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & !is.na(test.data60$vl_mth42[i]) & test.data60$vl_mth42[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & !is.na(test.data60$vl_mth36[i]) & test.data60$vl_mth36[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & !is.na(test.data60$vl_mth30[i]) & test.data60$vl_mth30[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & !is.na(test.data60$vl_mth24[i]) & test.data60$vl_mth24[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & !is.na(test.data60$vl_mth18[i]) & test.data60$vl_mth18[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & !is.na(test.data60$vl_mth12[i]) & test.data60$vl_mth12[i] < 1000) | 
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & !is.na(test.data60$vl_mth6[i]) & test.data60$vl_mth6[i] < 1000) |
       (is.na(test.data60$vl_mth48[i]) & is.na(test.data60$vl_mth42[i]) & is.na(test.data60$vl_mth36[i]) & is.na(test.data60$vl_mth30[i]) & is.na(test.data60$vl_mth24[i]) & is.na(test.data60$vl_mth18[i]) & is.na(test.data60$vl_mth12[i]) & is.na(test.data60$vl_mth6[i]) & !is.na(test.data60$basevl[i]) & test.data60$basevl[i] < 1000))
      & !is.na(test.data60$vl_mth54[i]) & test.data60$vl_mth54[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data60$prev_fail[i]=counter[i]
}

test.data60$visit=60

test.data60$vl <- test.data60$vl_mth60
test.data60$vllog <- test.data60$vl60

### getting the double failure status at month 60
for (i in 1:length(test.data60$study_id)) {
  if (!is.na(test.data60$prev_vl[i]) & test.data60$prev_vl_t[i]<60 & test.data60$prev_vl[i]>=1000 & test.data60$vl_mth60[i]>=1000)
  {test.data60$dub_fail[i] = 1}
  else if (!is.na(test.data60$prev_vl[i]) & test.data60$prev_vl_t[i]<60 & (test.data60$prev_vl[i]<1000 | test.data60$vl_mth60[i]<1000))
  {test.data60$dub_fail[i] = 0}
  else {test.data60$dub_fail[i] = NA}
}

check <- test.data60[is.na(test.data60$dub_fail),]
check2 <- test.data60[!is.na(test.data60$dub_fail),]
check3 <- test.data60[test.data60$dub_fail==1 & !is.na(test.data60$dub_fail),]


# repeating for 66 month values
test.data66 <- mydata[(!is.na(mydata$visitdate66) & !is.na(mydata$vl_mth66) & mydata$visitdate66 <= date2 & mydata$visitdate66 >= date1),]

# making sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data66$study_id)){
  
  if (!is.na(test.data66$vl_mth60[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth60[i]
    test.data66$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data66$vl_mth54[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth54[i]
    test.data66$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data66$vl_mth48[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth48[i]
    test.data66$prev_vl_t[i]=18
  }
  else if (!is.na(test.data66$vl_mth42[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth42[i]
    test.data66$prev_vl_t[i]=24
  }
  
  else if (!is.na(test.data66$vl_mth36[i])) {
    test.data66$prev_vl[i]=test.data66$vl_mth36[i]
    test.data66$prev_vl_t[i]=30
  }
  
  else if (!is.na(test.data66$vl_mth30[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth30[i]
    test.data66$prev_vl_t[i]=36
  }
  
  else if (!is.na(test.data66$vl_mth24[i])){
    test.data66$prev_vl[i]=test.data66$vl_mth24[i]
    test.data66$prev_vl_t[i]=42
  }
  
  else if (!is.na(test.data66$vl_mth18[i])) {
    test.data66$prev_vl[i]=test.data66$vl_mth18[i]
    test.data66$prev_vl_t[i]=48
  }
  else if (!is.na(test.data66$vl_mth12[i]))
  {test.data66$prev_vl[i]=test.data66$vl_mth12[i]
  test.data66$prev_vl_t[i]=54}
  else if (!is.na(test.data66$vl_mth6[i]))
  {test.data66$prev_vl[i]=test.data66$vl_mth6[i]
  test.data66$prev_vl_t[i]=60}
  else if (!is.na(test.data66$basevl[i]))
  {test.data66$prev_vl[i]=test.data66$basevl[i]
  test.data66$prev_vl_t[i]=66}
  else {test.data66$prev_vl[i]=NA}
}

test.data66 <- test.data66[!is.na(test.data66$prev_vl),]

counter <- NULL
for (i in 1:length(test.data66$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000 & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) | 
       (is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000)) 
      & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) |
       (is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) |
       (is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] < 1000) |
       (is.na(test.data66$vl_mth30[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth36[i]) & test.data66$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 42 months
  if (((!is.na(test.data66$vl_mth36[i]) & test.data66$vl_mth36[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & !is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth42[i]) & test.data66$vl_mth42[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 48 months
  if (((!is.na(test.data66$vl_mth42[i]) & test.data66$vl_mth42[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & !is.na(test.data66$vl_mth36[i]) & test.data66$vl_mth36[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & !is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) | 
       (is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth48[i]) & test.data66$vl_mth48[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 54 months
  if (((!is.na(test.data66$vl_mth48[i]) & test.data66$vl_mth48[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & !is.na(test.data66$vl_mth42[i]) & test.data66$vl_mth42[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & !is.na(test.data66$vl_mth36[i]) & test.data66$vl_mth36[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & !is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) | 
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth54[i]) & test.data66$vl_mth54[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 60 months
  if (((!is.na(test.data66$vl_mth54[i]) & test.data66$vl_mth54[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & !is.na(test.data66$vl_mth48[i]) & test.data66$vl_mth48[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & !is.na(test.data66$vl_mth42[i]) & test.data66$vl_mth42[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & !is.na(test.data66$vl_mth36[i]) & test.data66$vl_mth36[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & !is.na(test.data66$vl_mth30[i]) & test.data66$vl_mth30[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & !is.na(test.data66$vl_mth24[i]) & test.data66$vl_mth24[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & !is.na(test.data66$vl_mth18[i]) & test.data66$vl_mth18[i] < 1000) | 
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & !is.na(test.data66$vl_mth12[i]) & test.data66$vl_mth12[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & !is.na(test.data66$vl_mth6[i]) & test.data66$vl_mth6[i] < 1000) |
       (is.na(test.data66$vl_mth54[i]) & is.na(test.data66$vl_mth48[i]) & is.na(test.data66$vl_mth42[i]) & is.na(test.data66$vl_mth36[i]) & is.na(test.data66$vl_mth30[i]) & is.na(test.data66$vl_mth24[i]) & is.na(test.data66$vl_mth18[i]) & is.na(test.data66$vl_mth12[i]) & is.na(test.data66$vl_mth6[i]) & !is.na(test.data66$basevl[i]) & test.data66$basevl[i] < 1000))
      & !is.na(test.data66$vl_mth60[i]) & test.data66$vl_mth60[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data66$prev_fail[i]=counter[i]
}

test.data66$visit=66

test.data66$vl <- test.data66$vl_mth66
test.data66$vllog <- test.data66$vl66

### getting the double failure status at month 66
for (i in 1:length(test.data66$study_id)) {
  if (!is.na(test.data66$prev_vl[i]) & test.data66$prev_vl_t[i]<66 & test.data66$prev_vl[i]>=1000 & test.data66$vl_mth66[i]>=1000)
  {test.data66$dub_fail[i] = 1}
  else if (!is.na(test.data66$prev_vl[i]) & test.data66$prev_vl_t[i]<66 & (test.data66$prev_vl[i]<1000 | test.data66$vl_mth66[i]<1000))
  {test.data66$dub_fail[i] = 0}
  else {test.data66$dub_fail[i] = NA}
}

check <- test.data66[is.na(test.data66$dub_fail),]
check2 <- test.data66[!is.na(test.data66$dub_fail),]
check3 <- test.data66[test.data66$dub_fail==1 & !is.na(test.data66$dub_fail),]



# repeating for 72 month values
test.data72 <- mydata[(!is.na(mydata$visitdate72) & !is.na(mydata$vl_mth72) & mydata$visitdate72 <= date2 & mydata$visitdate72 >= date1),]

# making sure subjects have at least 1 previous VL measure
for (i in 1:length(test.data72$study_id)){
  
  if (!is.na(test.data72$vl_mth66[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth66[i]
    test.data72$prev_vl_t[i]=6
  }
  
  else if (!is.na(test.data72$vl_mth60[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth60[i]
    test.data72$prev_vl_t[i]=12
  }
  
  else if (!is.na(test.data72$vl_mth54[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth54[i]
    test.data72$prev_vl_t[i]=18
  }
  
  else if (!is.na(test.data72$vl_mth48[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth48[i]
    test.data72$prev_vl_t[i]=24
  }
  else if (!is.na(test.data72$vl_mth42[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth42[i]
    test.data72$prev_vl_t[i]=30
  }
  
  else if (!is.na(test.data72$vl_mth36[i])) {
    test.data72$prev_vl[i]=test.data72$vl_mth36[i]
    test.data72$prev_vl_t[i]=36
  }
  
  else if (!is.na(test.data72$vl_mth30[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth30[i]
    test.data72$prev_vl_t[i]=42
  }
  
  else if (!is.na(test.data72$vl_mth24[i])){
    test.data72$prev_vl[i]=test.data72$vl_mth24[i]
    test.data72$prev_vl_t[i]=48
  }
  
  else if (!is.na(test.data72$vl_mth18[i])) {
    test.data72$prev_vl[i]=test.data72$vl_mth18[i]
    test.data72$prev_vl_t[i]=54
  }
  else if (!is.na(test.data72$vl_mth12[i]))
  {test.data72$prev_vl[i]=test.data72$vl_mth12[i]
  test.data72$prev_vl_t[i]=60}
  else if (!is.na(test.data72$vl_mth6[i]))
  {test.data72$prev_vl[i]=test.data72$vl_mth6[i]
  test.data72$prev_vl_t[i]=66}
  else if (!is.na(test.data72$basevl[i]))
  {test.data72$prev_vl[i]=test.data72$basevl[i]
  test.data72$prev_vl_t[i]=72}
  else {test.data72$prev_vl[i]=NA}
}

test.data72 <- test.data72[!is.na(test.data72$prev_vl),]

counter <- NULL
for (i in 1:length(test.data72$study_id)) {
  counter[i] <- 0
  ### code to check for failures at 6 months
  if (!is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000 & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  ## checking for failures at 12 months
  if (((!is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) | 
       (is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000)) 
      & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 18 months
  if (((!is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 24 months
  if (((!is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 30 months
  if (((!is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 36 months
  if (((!is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 42 months
  if (((!is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth42[i]) & test.data72$vl_mth42[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 48 months
  if (((!is.na(test.data72$vl_mth42[i]) & test.data72$vl_mth42[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & !is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) | 
       (is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth48[i]) & test.data72$vl_mth48[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 54 months
  if (((!is.na(test.data72$vl_mth48[i]) & test.data72$vl_mth48[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & !is.na(test.data72$vl_mth42[i]) & test.data72$vl_mth42[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & !is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) | 
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth54[i]) & test.data72$vl_mth54[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 60 months
  if (((!is.na(test.data72$vl_mth54[i]) & test.data72$vl_mth54[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & !is.na(test.data72$vl_mth48[i]) & test.data72$vl_mth48[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & !is.na(test.data72$vl_mth42[i]) & test.data72$vl_mth42[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & !is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) | 
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth60[i]) & test.data72$vl_mth60[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  #checking for failures at 66 months
  if (((!is.na(test.data72$vl_mth60[i]) & test.data72$vl_mth60[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & !is.na(test.data72$vl_mth54[i]) & test.data72$vl_mth54[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & !is.na(test.data72$vl_mth48[i]) & test.data72$vl_mth48[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & !is.na(test.data72$vl_mth42[i]) & test.data72$vl_mth42[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & !is.na(test.data72$vl_mth36[i]) & test.data72$vl_mth36[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & !is.na(test.data72$vl_mth30[i]) & test.data72$vl_mth30[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & !is.na(test.data72$vl_mth24[i]) & test.data72$vl_mth24[i] < 1000) | 
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & !is.na(test.data72$vl_mth18[i]) & test.data72$vl_mth18[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & !is.na(test.data72$vl_mth12[i]) & test.data72$vl_mth12[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & !is.na(test.data72$vl_mth6[i]) & test.data72$vl_mth6[i] < 1000) |
       (is.na(test.data72$vl_mth60[i]) & is.na(test.data72$vl_mth54[i]) & is.na(test.data72$vl_mth48[i]) & is.na(test.data72$vl_mth42[i]) & is.na(test.data72$vl_mth36[i]) & is.na(test.data72$vl_mth30[i]) & is.na(test.data72$vl_mth24[i]) & is.na(test.data72$vl_mth18[i]) & is.na(test.data72$vl_mth12[i]) & is.na(test.data72$vl_mth6[i]) & !is.na(test.data72$basevl[i]) & test.data72$basevl[i] < 1000))
      & !is.na(test.data72$vl_mth66[i]) & test.data72$vl_mth66[i] >= 1000)
  {counter[i] = counter[i]+1}
  
  test.data72$prev_fail[i]=counter[i]
}

test.data72$visit=72

test.data72$vl <- test.data72$vl_mth72
test.data72$vllog <- test.data72$vl72

### getting the double failure status at month 72
for (i in 1:length(test.data72$study_id)) {
  if (!is.na(test.data72$prev_vl[i]) & test.data72$prev_vl_t[i]<72 & test.data72$prev_vl[i]>=1000 & test.data72$vl_mth72[i]>=1000)
  {test.data72$dub_fail[i] = 1}
  else if (!is.na(test.data72$prev_vl[i]) & test.data72$prev_vl_t[i]<72 & (test.data72$prev_vl[i]<1000 | test.data72$vl_mth72[i]<1000))
  {test.data72$dub_fail[i] = 0}
  else {test.data72$dub_fail[i] = NA}
}

check <- test.data72[is.na(test.data72$dub_fail),]
check2 <- test.data72[!is.na(test.data72$dub_fail),]
check3 <- test.data72[test.data72$dub_fail==1 & !is.na(test.data72$dub_fail),]


##### putting all of the individual timepoint dataset together

test.data <- rbind(test.data6, test.data12, test.data18, test.data24, test.data30, test.data36, test.data42, test.data48,
                    test.data54, test.data60, test.data66, test.data72)

#### creating variable lastVL which is 50 if VL below 1000 and VL if VL > 1000

for (i in 1:length(test.data$study_id)){
  if (is.na(test.data$prev_vl[i])) {test.data$lastVL[i]=NA
                                  test.data$lastVLlog[i]=NA}
  else if (test.data$prev_vl[i]<=50){test.data$lastVL[i]=50
                                    test.data$lastVLlog[i]=log10(50)}
  else if (test.data$prev_vl[i]>50){test.data$lastVL[i]=test.data$prev_vl[i]
                                      test.data$lastVLlog[i]=log10(test.data$prev_vl[i])}
}


#### creating variable for time since last VL; 1 if 6 months or less, 0 else
test.data$lastVL_t <- ifelse(test.data$prev_vl_t<=6,1,0)

#### creating variable for time since enrollment; 1 if 12 months or less, 0 else
test.data$enroll_t <- ifelse(test.data$visit<=12,1,0)


#### creating interaction variable lastVLlog*lastVL_t
for (i in 1:length(test.data$study_id)){
  test.data$lastVL_time_int[i] <- test.data$lastVLlog[i]*test.data$lastVL_t[i]
}

### turning all categorical variables into binary variables for use with glmnet
test.data$male <- ifelse(test.data$sex=="M",1,0)
test.data$female <- ifelse(test.data$sex=="F",1,0)

test.data$basewho0 <- ifelse(test.data$basewho=="0",1,0)
test.data$basewho1 <- ifelse(test.data$basewho=="1",1,0)
test.data$basewho2 <- ifelse(test.data$basewho=="2",1,0)
test.data$basewho3 <- ifelse(test.data$basewho=="3",1,0)
test.data$basewho4 <- ifelse(test.data$basewho=="4",1,0)

test.data$buyamba <- ifelse(test.data$hub_name=="BUYAMBA",1,0)
test.data$kabira <- ifelse(test.data$hub_name=="KABIRA",1,0)
test.data$kakuuto <- ifelse(test.data$hub_name=="KAKUUTO",1,0)
test.data$kaleere <- ifelse(test.data$hub_name=="KALEERE",1,0)
test.data$kalisizo <- ifelse(test.data$hub_name=="KALISIZO",1,0)
test.data$kasaali <- ifelse(test.data$hub_name=="KASAALI",1,0)
test.data$kasasa <- ifelse(test.data$hub_name=="KASASA",1,0)
test.data$kayanja <- ifelse(test.data$hub_name=="KAYANJA",1,0)
test.data$kibaale <- ifelse(test.data$hub_name=="KIBAALE",1,0)
test.data$kifamba <- ifelse(test.data$hub_name=="KIFAMBA",1,0)
test.data$kyabigondo <- ifelse(test.data$hub_name=="KAYBIGONDO",1,0)
test.data$kyebe <- ifelse(test.data$hub_name=="KYEBE",1,0)
test.data$lwamaggwa <- ifelse(test.data$hub_name=="LWAMAGGWA",1,0)
test.data$lwanda <- ifelse(test.data$hub_name=="LWANDA",1,0)
test.data$lyantonde <- ifelse(test.data$hub_name=="LYANTONDE",1,0)
test.data$nabigasa <- ifelse(test.data$hub_name=="NABIGASA",1,0)
test.data$nakatoogo <- ifelse(test.data$hub_name=="NAKATOOGO",1,0)

test.data$reg_ABC3TCEFV <- ifelse(test.data$basereg=="ABC/3TC/EFV",1,0)
test.data$reg_ABC3TCLPVr <- ifelse(test.data$basereg=="ABC/3TC/LPVr",1,0)
test.data$reg_ABC3TCNVP <- ifelse(test.data$basereg=="ABC/3TC/NVP",1,0)
test.data$reg_CBVABC <- ifelse(test.data$basereg=="CBV/ABC",1,0)
test.data$reg_CBVEFV <- ifelse(test.data$basereg=="CBV/EFV",1,0)
test.data$reg_CBVNVP <- ifelse(test.data$basereg=="CBV/NVP",1,0)
test.data$reg_D4T3TCABC <- ifelse(test.data$basereg=="D4T/3TC/ABC",1,0)
test.data$reg_D4T3TCEFV <- ifelse(test.data$basereg=="D4T/3TC/EFV",1,0)
test.data$reg_D4T3TCLPVr <- ifelse(test.data$basereg=="D4T/3TC/LPVr",1,0)
test.data$reg_D4T3TCNVP <- ifelse(test.data$basereg=="D4T/3TC/NVP",1,0)
test.data$reg_TDF3TCEFV <- ifelse(test.data$basereg=="TDF/3TC/EFV",1,0)
test.data$reg_TDF3TCNVP <- ifelse(test.data$basereg=="TDF/3TC/NVP",1,0)
test.data$reg_TVDEFV <- ifelse(test.data$basereg=="TVD/EFV",1,0)

test.data$prev_fail0 <- ifelse(test.data$prev_fail==0,1,0)
test.data$prev_fail1 <- ifelse(test.data$prev_fail==1,1,0)
test.data$prev_fail2 <- ifelse(test.data$prev_fail==2,1,0)
test.data$prev_fail3 <- ifelse(test.data$prev_fail==3,1,0)


#### creating a variable for whether or not the current VL was a failure
test.data$fail_draw <- ifelse(test.data$vl>=1000,1,0)


#### adding a variable for high, low and medium ris groups based on VL we are trying to prdict
#### low risk is VL < 0 (lower limit of detection), medium risk is 0 <= VL <= 10000, high risk is VL > 10000

for (i in 1:length(test.data$study_id)){
  if (test.data$vl[i] < 0){test.data$label[i]="low"}
  else if (test.data$vl[i] >= 0 & test.data$vl[i] <= 10000){test.data$label[i]="medium"}
  else if (test.data$vl[i] > 10000){test.data$label[i]="high"}
}

#### creating a category variable (low, medium, high) for the last VL

for (i in 1:length(test.data$study_id)){
  if (test.data$lastVL[i] <= 50){test.data$lastVLcat[i]="low"}
  else if (test.data$lastVL[i] > 50 & test.data$lastVL[i] <= 10000){test.data$lastVLcat[i]="medium"}
  else if (test.data$lastVL[i] > 10000){test.data$lastVLcat[i]="high"}
}


# subsetting for only the variable we need
test.data2 <- select(test.data, study_id, sex, male, female, ageyrs,  age35, age50, age65, 
                      hub_name, buyamba, kabira, kakuuto, kaleere, kalisizo, kasaali, kasasa, kayanja,
                      kibaale, kifamba, kyabigondo, kyebe, lwamaggwa, lwanda, lyantonde, nabigasa, nakatoogo,
                      basewho, basewho0, basewho1, basewho2, basewho3, basewho4, 
                      basereg, reg_TVDEFV, reg_TDF3TCNVP, reg_TDF3TCEFV, reg_D4T3TCNVP, 
                      reg_D4T3TCLPVr, reg_D4T3TCEFV, reg_D4T3TCABC, reg_CBVNVP, reg_CBVEFV, 
                      reg_CBVABC, reg_ABC3TCNVP, reg_ABC3TCLPVr, reg_ABC3TCEFV,
                      prev_fail, prev_fail0, prev_fail1, prev_fail2, prev_fail3,
                      basecd4, bascd4log, basevl, basvllog, lastVL, lastVLlog,
                      lastVL_t, enroll_t, vl, vllog, fail_draw, dub_fail, lastVLcat, label)

# set working directory to location you want to write the dataset and uncomment below line
#setwd("")
#write.table(test.data2, paste0("test_data", format(Sys.time(),"%Y-%m-%d"), ".R"))





